# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Networking
  name: SimpleTorrent
  version: 1.3.8
  tagline: Download torrents with your Citadel
  description: >-
    SimpleTorrent is a a self-hosted remote torrent client that starts
    torrents remotely, download sets of files on your Citadel, which are then retrievable
    or streamable via web browser over HTTP. This project is a re-branded fork of
    cloud-torrent by jpillora. Features:


    - Individual file download control

    - Run external program on tasks completion: DoneCmd

    - Stops task when seeding ratio reached: SeedRatio

    - Download/Upload speed limiter: UploadRate/DownloadRate

    - Detailed transfer stats in web UI.

    - Torrent Watcher

    - Extra trackers from external source

    - Protocol Handler to magnet:

    - Magnet RSS subscribing supported
  developer: Preston
  website: https://github.com/boypt
  dependencies: []
  repo: https://github.com/boypt/simple-torrent
  support: https://github.com/boypt/simple-torrent/issues
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg

containers:
- image: boypt/cloud-torrent:1.3.8@sha256:85041b790e5ae08422700901633ad7d76fc60083756926e99aa1ee0d26b94b90
  user: 1000:1000
  command: --port=${APP_SIMPLE_TORRENT_SERVER_PORT} --config-path /config/simple-torrent.json
  name: server
  data:
  - data/config:/config
  - data/downloads:/downloads
  - data/torrents:/torrents

