# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1
metadata:
  category: Social
  name: Synapse
  version: 1.49.2
  tagline: Matrix reference homeserver
  description: >-
    Synapse is a reference "homeserver" implementation of Matrix from the core
    development team at matrix.org, written in Python/Twisted. It is intended to
    showcase the concept of Matrix and let folks see the spec in the context of
    a codebase and let you run your own homeserver and generally help bootstrap
    the ecosystem.


    The easiest way to try out your new Synapse installation is by connecting to it from a web client.


    An easy way to get started is to install the "Element" app on your Umbrel and change its Homeserver URL from matrix.org server to your Synapse's Homeserver URL of http://umbrel.local:8008 (or http://<synapse-tor-hidden-service-url> if you are accessing remotely).


    In Matrix, every user runs one or more Matrix clients, which connect through to a Matrix homeserver. The homeserver stores all their personal chat history and user account information - much as a mail client connects through to an IMAP/SMTP server. Just like email, you can either run your own Matrix homeserver and control and own your own communications and history or use one hosted by someone else (e.g. matrix.org) - there is no single point of control or mandatory service provider in Matrix, unlike WhatsApp, Facebook, Hangouts, etc.
  developer: Matrix
  website: https://matrix.org
  dependencies: []
  repo: https://github.com/matrix-org/synapse
  support: https://matrix.to/#/#synapse:matrix.org
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  torOnly: false
containers:
  - image: matrixdotorg/synapse:v1.49.2@sha256:7cd176e66c7783cdc9eb2770ff8ef7dfeaa8f94a5d12755ad1e779d8bcdf01b9
    user: 1000:1000
    entrypoint: bash
    command: -c './start.py generate && ./start.py migrate_config && exec ./start.py'
    environment:
      UID: "1000"
      GID: "1000"
      SYNAPSE_HTTP_PORT: ${APP_SYNAPSE_SERVER_PORT}
      SYNAPSE_SERVER_NAME: ${APP_HIDDEN_SERVICE}
      SYNAPSE_REPORT_STATS: yes
      SYNAPSE_ENABLE_REGISTRATION: yes
      SYNAPSE_NO_TLS: yes
    name: server
    data:
      - data/synapse:/data
