# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Social
  name: Element
  version: 2.1.5
  tagline: A glossy Matrix client compatible with Synapse
  description: >-
    Element is a new type of messaging app. You choose where your messages
    are stored, putting you in control of your data.
    You can connect it to the Synapse  installation running on your Umbrel.
    An easy way to get started is to install the "Synapse" Matrix homserver on your Umbrel
    and change Element's Homserver URL from matrix.org 
    to your Synapse's homeserver URL (http://umbrel.local:8008
    or http://<synapse-tor-hidden-service-url>).
    
    It gives you access to the Matrix open network, so you can talk to anyone. 
    Element provides a new level of security,
    adding cross-signed device verification to default end-to-end encryption.



    The very best end-to-end encryption and Element's unique cross-signed
    device verification means only those that should be in the conversation can
    read the messages - no eavesdroppers or imposters.
    
    
    Most important of all, Element is open; built on the Matrix network, 
    it connects to all other Matrix-based apps as well as bridging into proprietary systems.
    You can stay in Element while talking to friends and family in other apps.
    


    Element is open source. You know exactly what you're getting. 
    Full transparency, the freedom to extend and customise with the support of a vibrant community of developers.
  developer: New Vector Ltd
  website: https://element.io
  dependencies: []
  repo: https://github.com/vector-im/element-web
  support: https://matrix.to/#/#element-web:matrix.org
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  torOnly: false

containers:
- image: ghcr.io/runcitadel/element-web:develop@sha256:a5cc383669e7ae6ddcf74123d860e4758eaf31e9c1c1f7f3534976a0bb509afc
  port: 80
  name: web
