# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Development
  name: code-server
  version: 3.12.0
  tagline: Run VS Code on your Umbrel
  description: >-
    Run VS Code on your Umbrel and access it in the browser so you can
    code on any device with a consistent development environment. This way you can
    use your Umbrel not only to code from any device, anywhere, but to also speed
    up tests, compilations, downloads, and more.


    By running all intensive tasks run on your Umbrel, preserve battery life of your
    devices when you're on the go.
  developer: Coder
  website: https://coder.com
  dependencies: []
  repo: https://github.com/cdr/code-server
  support: https://github.com/cdr/code-server/discussions
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: $APP_SEED

containers:
- name: server
  image: codercom/code-server:3.12.0@sha256:44415390c118663dd58119ea4d3891ed32f1f56181144af671cf9c0de41d6132
  user: 1000:1000
  environment:
    PASSWORD: $APP_SEED
  data:
  - data:/home/coder
