# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Lightning Node Management
  name: Ride The Lightning
  version: 0.11.2
  tagline: A powerful dashboard for the Lightning Network
  description: >-
    RTL is a full function, device agnostic, web user interface to help
    manage lightning node operation. It enables full control over your lightning node
    with rich functionality for Bitcoin base layer and Lightning Network. Some cool
    features available on RTL are:


    - Rich dashboard with two layout options

    - Send/Receive funds on-chain

    - Rich channel management with advanced features like balance score, circular
    re-balancing etc.

    - Payments and Invoice management with QR codes

    - Routing analysis for the payments forwarded

    - Channel backups

    - Detailed reports on routing and transaction history

    - Optional Loop interface for submarine swaps

    - Customizable UI with multiple color schemes and dark/light modes
  developer: Shahana and Suheb
  website: https://github.com/Ride-The-Lightning/RTL
  dependencies:
  - lnd
  - bitcoind
  repo: https://github.com/Ride-The-Lightning/RTL
  support: https://github.com/Ride-The-Lightning/RTL/issues/new
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  defaultPassword: moneyprintergobrrr
  mainContainer: web

containers:
- image: shahanafarooqui/rtl:0.11.2@sha256:225b47abcca053e3ea831431742a08b3f3e70b12654df6fd703f617ad965f34e
  user: 1000:1000
  environment:
    PORT: $APP_RIDE_THE_LIGHTNING_WEB_PORT
    RTL_CONFIG_PATH: /data
    CHANNEL_BACKUP_PATH: /data/backup
    LN_IMPLEMENTATION: LND
    LN_SERVER_URL: https://$LND_IP:$LND_REST_PORT
    MACAROON_PATH: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK
    CONFIG_PATH: /lnd/lnd.conf
    SWAP_SERVER_URL: https://$APP_RIDE_THE_LIGHTNING_LOOP_IP:8081
    SWAP_MACAROON_PATH: /loop/.loop/$BITCOIN_NETWORK
  name: web
  data:
  - loop:/loop
  - rtl:/data
  permissions:
  - lnd
  - bitcoind

- image: runcitadel/loop:v0.15.0-beta@sha256:40561eed1de740eba99e4784703134a7d987c4c1f064d6759c449f56f34c7338
  user: 1000:1000
  environment:
    HOME: /data
  command:
  - --network=$BITCOIN_NETWORK
  - --lnd.host="$LND_IP:$LND_GRPC_PORT"
  - --lnd.macaroonpath="/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon"
  - --lnd.tlspath="/lnd/tls.cert"
  - --restlisten=0.0.0.0:8081
  name: loop
  data:
  - loop:/data
  permissions:
  - lnd
