# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Lightning Node Management
  name: LNbits
  version: "3167645"
  tagline: Multi-user wallet management system
  description: 'LNbits is a simple multi-user and account system for Lightning Network
    that can be used for creating separate Lightning wallets for friends and family
    members. You can also create multiple accounts for yourself to mitigate the risk
    of exposing applications to your full balance via unique API keys for each wallet.


    LNbits is packaged with tools to help manage funds, such as a table of transactions,
    line chart of spending, export to CSV, and more to come. It provides an extendable
    platform for expanding Lightning Network functionality via LNbits extension framework,
    and can also be used as a fallback wallet for the LNURL scheme.'
  developer: LNbits
  website: https://github.com/lnbits/lnbits
  dependencies:
  - lnd
  repo: https://github.com/lnbits/lnbits
  support: https://t.me/lnbits
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg

containers:
- image: lnbitsdocker/lnbits:3167645@sha256:1fde47507a7595bf446f32ae8d76822bf7ed39b77f5ec7cb3645de9198a8b42c
  #user: 1000:1000
  init: true
  environment:
    LNBITS_BIND: 0.0.0.0:$APP_LNBITS_WEB_PORT
    LNBITS_DATA_FOLDER: /data
    LNBITS_BACKEND_WALLET_CLASS: LndWallet
    LND_GRPC_ENDPOINT: $LND_IP
    LND_GRPC_PORT: $LND_GRPC_PORT
    LND_GRPC_CERT: /lnd/tls.cert
    LND_GRPC_MACAROON: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon
    LNBITS_SITE_TITLE: LNbits on Citadel
    LNBITS_DEFAULT_WALLET_NAME: LNbits wallet
    LNBITS_DISABLED_EXTENSIONS: amilk
  name: web
  data:
  - data:/data
  permissions:
  - lnd
