# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1
metadata:
  category: Lightning Node Management
  name: LNbits
  version: 0764f4f
  tagline: Multi-user wallet management system
  description: >-
    LNbits is a simple multi-user and account system for Lightning Network that
    can be used for creating separate Lightning wallets for friends and family
    members. You can also create multiple accounts for yourself to mitigate the
    risk of exposing applications to your full balance via unique API keys for
    each wallet.


    LNbits is packaged with tools to help manage funds, such as a table of transactions, line chart of spending, export to CSV, and more to come. It provides an extendable platform for expanding Lightning Network functionality via LNbits extension framework, and can also be used as a fallback wallet for the LNURL scheme.
  developer: LNbits
  website: https://github.com/lnbits/lnbits
  dependencies:
    - lnd
  repo: https://github.com/lnbits/lnbits
  support: https://t.me/lnbits
  gallery:
    - 1.jpg
    - 2.jpg
    - 3.jpg
  defaultPassword: $APP_SEED
containers:
  - image: ghcr.io/runcitadel/lnbits:feat-admin-password@sha256:9db49caf65037d9bcb8b018f87c5cc0521afea33af36d506e998ba0a79ca7791
    user: 1000:1000
    init: true
    port: 5000
    environment:
      LNBITS_DATA_FOLDER: /data
      LNBITS_BACKEND_WALLET_CLASS: LndWallet
      LND_GRPC_ENDPOINT: $LND_IP
      LND_GRPC_PORT: $LND_GRPC_PORT
      LND_GRPC_CERT: /lnd/tls.cert
      LND_GRPC_MACAROON: /lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon
      LNBITS_SITE_TITLE: LNbits on Citadel
      LNBITS_DEFAULT_WALLET_NAME: LNbits wallet
      LNBITS_DISABLED_EXTENSIONS: amilk
      LNBITS_ADMIN_LOGIN_KEY: $APP_SEED
      LNBITS_ADMIN_EXTENSIONS: ngrok
    name: web
    data:
      - data:/data
    permissions:
      - lnd
    restart: on-failure
