# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Payments
  name: BTCPay Server
  version: 1.3.2
  tagline: Accept Bitcoin payments with 0 fees & no 3rd party
  description: >-
    BTCPay Server is a payment processor that allows you to receive payments
    in Bitcoin (and altcoins) directly, with no fees, transaction cost or a middleman.
    It is a non-custodial invoicing system which eliminates the involvement of a third-party.


    Payments with BTCPay Server go directly to your wallet, which increases the privacy
    and security. Your private keys are never uploaded to your Umbrel. There is no
    address re-use, since each invoice generates a new address deriving from your
    xpubkey.


    You can not only to attach an unlimited number of stores and use the Lightning
    Network but also become a payment processor for others. Thanks to the apps built
    on top of it, you can use BTCPay to receive donations, start a crowdfunding campaign
    or have an in-store Point of Sale.
  developer: BTCPay Server Foundation
  website: https://btcpayserver.org
  dependencies:
  - lnd
  - bitcoind
  repo: https://github.com/btcpayserver/btcpayserver
  support: https://chat.btcpayserver.org
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  mainContainer: web

containers:
- name: nbxplorer
  image: nicolasdorier/nbxplorer:2.2.10@sha256:bfec52de14dba187176e1bdd53a4fcb97bc2a18932e247a6ab2882dda6515ee1
  user: 1000:1000
  environment:
    NBXPLORER_DATADIR: /data
    NBXPLORER_NETWORK: $BITCOIN_NETWORK
    NBXPLORER_PORT: 32838
    NBXPLORER_BIND: 0.0.0.0
    NBXPLORER_CHAINS: btc
    NBXPLORER_SIGNALFILEDIR: /data
    NBXPLORER_BTCRPCURL: http://$BITCOIN_IP:$BITCOIN_RPC_PORT
    NBXPLORER_BTCNODEENDPOINT: $BITCOIN_IP:$BITCOIN_P2P_PORT
    NBXPLORER_BTCRPCUSER: $BITCOIN_RPC_USER
    NBXPLORER_BTCRPCPASSWORD: $BITCOIN_RPC_PASS
  data:
  - data/nbxplorer:/data
  permissions:
  - bitcoind

- name: web
  image: btcpayserver/btcpayserver:1.3.2@sha256:3a8ce7a5629f9d115583d1697cd118688117e333d9293aa69400a137eecc3636
  depends_on:
  - nbxplorer
  - postgres
  entrypoint:
  - dotnet
  - BTCPayServer.dll
  environment:
    HOME: /data
    BTCPAY_DATADIR: /data
    BTCPAY_PLUGINDIR: /data/plugins
    BTCPAY_DOCKERDEPLOYMENT: 'false'
    BTCPAY_POSTGRES: User ID=postgres;Host=$APP_BTCPAY_SERVER_POSTGRES_IP;Port=5432;Database=btcpayserver$BITCOIN_NETWORK
    BTCPAY_NETWORK: $BITCOIN_NETWORK
    BTCPAY_BIND: 0.0.0.0:$APP_BTCPAY_SERVER_WEB_PORT
    BTCPAY_CHAINS: btc
    BTCPAY_BTCEXPLORERURL: http://$APP_BTCPAY_SERVER_NBXPLORER_IP:32838
    BTCPAY_BTCLIGHTNING: type=lnd-rest;server=https://$LND_IP:$LND_REST_PORT/;macaroonfilepath=/lnd/data/chain/bitcoin/$BITCOIN_NETWORK/admin.macaroon;allowinsecure=true
    BTCPAY_SOCKSENDPOINT: $TOR_PROXY_IP:$TOR_PROXY_PORT
  data:
  - data/nbxplorer:/data/.nbxplorer
  - data/btcpay:/data
  permissions:
  - lnd
  user: 1000:1000

- name: postgres
  image: postgres:9.6.20@sha256:82c335ccb6b60941cb860cbb8252c12f63fd3e27a0d15bce5bc6de110c02a2b4
  user: 1000:1000
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust
  data:
  - data/postgres:/var/lib/postgresql/data
