# SPDX-FileCopyrightText: 2020-2021 Umbrel. https://getumbrel.com
#
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

# yaml-language-server: $schema=../../app-standard-v1.json

version: 1

metadata:
  category: Wallet Servers
  name: Samourai Server
  version: 1.11.0
  tagline: Your private backing server for Samourai Wallet.
  description: >-
    Samourai Server is a Citadel app that runs Samourai Dojo
    and Whirlpool backing servers, and provides you easy step-by-step instructions
    to connect your Samourai Wallet to them. Samourai Wallet is unrivaled in transaction
    privacy, but its default configuration is still subject to network level privacy
    loss.


    By default, Samourai Wallet will connect to its centrally controlled Dojo hosted
    in Iceland. By hosting your own Samourai Server, you can bypass its servers completely
    when using Samourai Wallet or Sentinel, and gain total financial sovereignty without
    any complexity.


    Bundles Whirlpool CLI v0.10.11.
  developer: Samourai
  website: https://samouraiwallet.com
  dependencies:
  - electrum
  - bitcoind
  repo: https://github.com/louneskmt/umbrel-samourai-dojo/tree/v1.10.1-umbrel
  support: https://t.me/SamouraiWallet
  gallery:
  - 1.jpg
  - 2.jpg
  - 3.jpg
  updateContainer: node

containers:
- name: db
  image: mariadb:10.6.4@sha256:4bbee12b1adf299211f844ebbe89563675c46965470dcfa40f5278d63c56d030
  init: true
  stop_grace_period: 5m
  user: 1000:1000
  environment:
    MYSQL_DATABASE: samourai-main
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_USER: samourai
    MYSQL_PASSWORD: password
  data:
  - mysql/update-db.sh:/update-db.sh
  - mysql/mysql-dojo.cnf:/etc/mysql/conf.d/mysql-dojo.cnf
  - mysql/db-scripts:/docker-entrypoint-initdb.d
  - mysql/data:/var/lib/mysql

- name: node
  image: ghcr.io/runcitadel/samourai-dojo:develop@sha256:26f4e2bcfc9a053303b8d2b54c24b161ea0f9cf92e6e468bdc0b5d152ae98596
  init: true
  command: /home/node/app/wait-for-it.sh ${APP_SAMOURAI_SERVER_DB_IP}:3306 --timeout=720 --strict -- /home/node/app/restart.sh
  user: 1000:1000
  environment:
    COMMON_BTC_NETWORK: $BITCOIN_NETWORK
    DOJO_NODEJS_VERSION_TAG: 1.12.1
    NET_DOJO_TOR_IPV4: $TOR_PROXY_IP
    NET_DOJO_TOR_PORT: $TOR_PROXY_PORT
    NET_DOJO_MYSQL_IPV4: $APP_SAMOURAI_SERVER_DB_IP
    MYSQL_DATABASE: samourai-main
    MYSQL_USER: samourai
    MYSQL_PASSWORD: password
    NODE_GAP_EXTERNAL: 100
    NODE_GAP_INTERNAL: 100
    NODE_ADDR_FILTER_THRESHOLD: 1000
    NODE_ADDR_DERIVATION_MIN_CHILD: 2
    NODE_ADDR_DERIVATION_MAX_CHILD: 2
    NODE_ADDR_DERIVATION_THRESHOLD: 10
    NODE_TXS_SCHED_MAX_ENTRIES: 10
    NODE_TXS_SCHED_MAX_DELTA_HEIGHT: 18
    NODE_JWT_ACCESS_EXPIRES: 900
    NODE_JWT_REFRESH_EXPIRES: 7200
    NODE_PREFIX_STATUS: status
    NODE_PREFIX_SUPPORT: support
    NODE_PREFIX_STATUS_PUSHTX: status
    NODE_TRACKER_MEMPOOL_PERIOD: 10000
    NODE_TRACKER_UNCONF_TXS_PERIOD: 300000
    NODE_ACTIVE_INDEXER: local_indexer
    NODE_FEE_TYPE: ECONOMICAL
    NODE_API_KEY: $APP_SEED_1
    NODE_ADMIN_KEY: $APP_SEED_2
    NODE_JWT_SECRET: $APP_SEED_3
    BITCOIND_IP: $BITCOIN_IP
    BITCOIND_RPC_PORT: $BITCOIN_RPC_PORT
    BITCOIND_RPC_USER: $BITCOIN_RPC_USER
    BITCOIND_RPC_PASSWORD: $BITCOIN_RPC_PASS
    BITCOIND_ZMQ_RAWTXS: $BITCOIN_ZMQ_RAWTX_PORT
    BITCOIND_ZMQ_BLK_HASH: $BITCOIN_ZMQ_HASHBLOCK_PORT
    EXPLORER_INSTALL: 'off'
    INDEXER_IP: $ELECTRUM_IP
    INDEXER_RPC_PORT: $ELECTRUM_PORT
    INDEXER_BATCH_SUPPORT: inactive
  depends_on:
  - db
  permissions:
  - electrum
  - bitcoind
  needsHiddenService: true

- name: whirlpool
  image: louneskmt/whirlpool:0.10.11@sha256:a7cfb9e287aa5f2e4137a5d2fdddbfd348624e24e7dd7bed7fa0f4e2e22734d5
  init: true
  user: 1000:1000
  command:
  - --listen
  - --cli.apiKey=$APP_SEED_4
  - --cli.api.http-enable=true
  - --cli.api.http-port=8898
  - --cli.tor=true
  - --cli.torConfig.coordinator.enabled=true
  - --cli.torConfig.coordinator.onion=true
  - --cli.torConfig.backend.enabled=false
  - --cli.torConfig.backend.onion=false
  - --cli.mix.liquidityClient=true
  - --cli.mix.clientsPerPool=1
  - --resync
  environment:
    WHIRLPOOL_BITCOIN_NETWORK: $BITCOIN_NETWORK
    WHIRLPOOL_DOJO: 'on'
    WHIRLPOOL_DOJO_IP: $APP_SAMOURAI_SERVER_MAIN_IP
  data:
  - whirlpool:/home/whirlpool/.whirlpool-cli
  needsHiddenService: true
  hiddenServicePort: 8898

- image: nginx:1.21.3-alpine@sha256:1ff1364a1c4332341fc0a854820f1d50e90e11bb0b93eb53b47dc5e10c680116
  init: true
  command: /bin/sh -c "envsubst < /var/www/connect/js/conf.template.js > /var/www/connect/js/conf.js
    && /wait-for node:8080 --timeout=720 -- nginx"
  environment:
    COMMON_BTC_NETWORK: $BITCOIN_NETWORK
    DOJO_LOCAL_PORT: 3009
    DOJO_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE_NODE
    WHIRLPOOL_HIDDEN_SERVICE: $APP_HIDDEN_SERVICE_WHIRLPOOL
    NODE_PREFIX_SUPPORT: support
    NODE_ADMIN_KEY: $APP_SEED_2
    WHIRLPOOL_API_KEY: $APP_SEED_4
  ports:
  - 3009:80
  port: 8081
  depends_on:
  - node
  hiddenServicePorts: 
    dojo: 3009
  name: main
  data:
  - nginx/connect:/var/www/connect
  - nginx/connect.conf:/etc/nginx/sites-enabled/connect.conf
  - nginx/${BITCOIN_NETWORK}.conf:/etc/nginx/sites-enabled/dojo.conf
  - nginx/nginx.conf:/etc/nginx/nginx.conf
  - nginx/wait-for:/wait-for
