name: Check app updates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  schedule: 
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for updates
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          git clone https://github.com/runcitadel/dev-tools
          cd dev-tools
          yarn && yarn tsc
          yarn citadel-dev appcheck -d ../apps/apps
          cd ..
          rm -rf dev-tools
          git commit -a -m "Update apps"
          git push
          
